# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e8b1c2ce008cb638148cf2328cec0145d31c86f5d79c63782137981c4a3e1f5c60c119487d39d9a64300d4650e87cb440d57eab6f635a92ba9642965f09e9d5

test:
  secret_key_base: 78347294a74c50c02f99de5aa585018eb9ae794733093ed6bcc91eb469fe357c2e26484be82bf56a6eff8f3034e886e3433066d1c3d320093b982e9eb8922e41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
